spec:
 template:
   spec:
     containers:
       - resources:
           limits:
             cpu: "1000m"
             memory: "2Gi"
           requests:
             cpu: "500m"
             memory: "512Mi"